# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xkdKEkkFhzl-90az1_YZcQlJPUgDXusz
"""

! pip install openai langchain-openai

! pip install langchain langchain-community langchain-google-genai chromadb pypdf

! pip list

! python -m pip install --upgrade pip

! pip install --upgrade langchain langchain-community

! pip install langchain langchain-community langchain-google-genai chromadb pypdf

! pip install langchain-text-splitters

! pip uninstall google-generativeai langchain-google-genai -y
! pip install -U google-generativeai langchain-google-genai

! pip show langchain-google-genai
! pip show google-genai

import os

os.environ["GOOGLE_API_KEY"] = "AIzaSyCZSTQ-aSc07eG7sSKuGXHVYRWulHO9MOw"

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_google_genai import GoogleGenerativeAIEmbeddings

from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import Chroma

from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

from google.colab import files
uploaded = files.upload()

loader = PyPDFLoader("Vasanth_Resume.pdf")
documents = loader.load()

import os
print(os.getcwd())

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

docs = text_splitter.split_documents(documents)

from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

vectorstore = Chroma.from_documents(docs if len(docs) > 0 else loader.load(), embeddings)

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0
)

prompt = ChatPromptTemplate.from_template("""
Answer the question based only on the context below.

Context:
{context}

Question:
{question}
""")

retriever = vectorstore.as_retriever()

rag_chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

response = rag_chain.invoke(
    "What is the skills mentioned in Vasanth_Resume?"
)
print(response)

response = rag_chain.invoke(
    "What is the Number mentioned in that resume?"
)
print(response)